- hosts: local
  tasks:
     - pip: requirements=requirements.txt
#    - name: Rabbitmq enable web management plugin
#      command: rabbitmq-plugins enable rabbitmq_management
#      notify: restart rabbitmq


#  handlers:
#    - name: restart rabbitmq
#      service: name=rabbitmq-server state=restarted

